server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            exposedHeaders:
              - "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_FIRST
      routes:
        - id: ms-usuarios
          uri: http://localhost:8080
          predicates:
            - Path=/api/usuarios/**
        - id: ms-comics
          uri: http://localhost:8081
          predicates:
            - Path=/api/comics/**
        - id: ms-ventas
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
